- name: AMWA test suite
  shell: bash
  working-directory: ${{ env.RUNNER_WORKSPACE }}
  run:
    |
    set -x
    root_dir=`pwd`
    # Install AMWA test suite.
    git clone https://github.com/AMWA-TV/nmos-testing.git
    cd nmos-testing

    # Create output directories
    mkdir results
    mkdir badges

    if [[ "${{ env.DOCKER_TEST_SUITE }}" == "true" ]]; then
      # run test suite in amwa/nmos-testing docker container
      docker pull amwa/nmos-testing
      docker run -d --name "nmos_testing" --entrypoint="/usr/bin/tail" -v `pwd`/results:/home/nmos-testing/results amwa/nmos-testing -f /dev/null
      run_test="docker exec -i nmos_testing python3 nmos-test.py"
    elif  [[ "${{ env.VAGRANT_TEST_SUITE }}" == "true" ]]; then
      # run test suite in vagrant VM
      cp ${{ env.GITHUB_WORKSPACE }}/.github/workflows/mac_Vagrantfile ./Vagrantfile
      vagrant plugin install vagrant-scp
      vagrant up
      vagrant ssh -- mkdir results
      run_test="vagrant ssh -- python3 nmos-test.py"
    else
      # run test suite directly
      pip install -r requirements.txt

      # Install SDPoker
      if [[ "${{ matrix.os }}" == "windows-latest" || "$EUID" == "0" ]]; then
        npm install -g AMWA-TV/sdpoker
      else
        sudo npm install -g AMWA-TV/sdpoker
      fi
      run_test="python nmos-test.py"
    fi
    pip install -r utilities/run-test-suites/gsheetsImport/requirements.txt

    ${{ env.GITHUB_WORKSPACE }}/Sandbox/run_nmos_testing.sh $run_test ${root_dir}/build/nmos-cpp-node ${root_dir}/build/nmos-cpp-registry results badges ${{ env.HOST_IP_ADDRESS }} "${{ env.GITHUB_COMMIT }}-${{ env.BUILD_NAME }}-"

    if [[ "${{ env.DOCKER_TEST_SUITE }}" == "true" ]]; then
      docker stop nmos_testing
      docker rm nmos_testing
    fi
    if  [[ "${{ env.VAGRANT_TEST_SUITE }}" == "true" ]]; then
      vagrant scp :results/* results/
      vagrant destroy -f
    fi
    exit 0
