- name: install test
  uses: lukka/run-cmake@v2.0
  with:
    cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
    cmakeListsTxtPath: '${{ env.GITHUB_WORKSPACE }}/Sandbox/my-nmos-node/CMakeLists.txt'
    buildDirectory: '${{ env.RUNNER_WORKSPACE }}/build-my-nmos-node/'
    cmakeAppendedArgs: '-GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_PACKAGE_PREFER_CONFIG="1" -DCMAKE_MODULE_PATH="${{ env.RUNNER_WORKSPACE }}/build" -DCMAKE_PREFIX_PATH="${{ env.RUNNER_WORKSPACE }}/install;${{ env.RUNNER_WORKSPACE }}/build" ${{ env.CMAKE_EXTRA_ARGS }}'

